modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
logoFile = "logo.png"

[[mods]]
modId = "shortcutterminal"
version = "1.0.0(Beta)"
displayName = "Shortcut Terminal"
authors = "UNSA-STUDIO"
description = '''
Shortcut Terminal - Linux commands in Minecraft!

⚠ 需要安装 帕秋莉手册 (Patchouli) 作为前置！
'''

[[dependencies.shortcutterminal]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.shortcutterminal]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.21.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.shortcutterminal]]
    modId = "patchouli"
    type = "required"
    versionRange = "[1.21.1-93,)"
    ordering = "AFTER"
    side = "BOTH"
