modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "st"
version = "1.0.0"
displayName = "Shortcut Terminal"
authors = "UNSA-STUDIO"
description = '''
Shortcut Terminal - Linux commands in Minecraft!

Features:
- /ST Help - List all available commands
- /ST ls, mkdir, touch, rm, cat - Basic file operations
- /ST cd - Change directory (restricted to user folder)
- /ST User - Admin command to manage players
- /ST open terminal page - Enter terminal mode
'''

[[dependencies.st]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.st]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.21.2)"
    ordering = "NONE"
    side = "BOTH"
