modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}

Features:
- /ST Help - List all available commands
- /ST ls, mkdir, touch, rm, cat - Basic file operations
- /ST cd - Change directory (restricted to user folder)
- /ST User - Admin command to manage players
- /ST open terminal page - Enter terminal mode
'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
